language: generic

sudo: false
cache:
  directories:
  - $HOME/.stack/

matrix:
  addons:
    apt:
      sources:
      - hvr-ghc

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar -xzO --wildcards '*/stack' > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack

install:
  - stack -j 2 setup --no-terminal
  - stack -j 2 build --only-snapshot --no-terminal

script:
  - stack -j 2 test --no-terminal --coverage

after_script:
  - travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar -xj
  - ./shc haprs haprs-test
